"""
quality_reporter.py
-------------------
Quality-check report for each state dataset.

Produces
--------
- reports/<state>/dataset_summary.md
- reports/<state>/missing_values.csv

Public API
----------
generate_quality_report(df, state_code, state_name, report_dir)
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .config import (
    COL_AGENCY,
    COL_CAUSE,
    COL_COUNTY,
    COL_FIRE_NAME,
    COL_FIRE_SIZE,
    COL_FIRE_YEAR,
    COL_LATITUDE,
    COL_LONGITUDE,
    COL_OWNER,
    TOP_N_AGENCIES,
    TOP_N_COUNTIES,
)
from .logger import get_logger

log = get_logger(__name__)


def _md_header(text: str, level: int = 2) -> str:
    return f"\n{'#' * level} {text}\n"


def _safe_value_counts(series: pd.Series, n: int = 10) -> pd.Series:
    return series.value_counts(dropna=False).head(n)


def generate_quality_report(
    df: pd.DataFrame,
    state_code: str,
    state_name: str,
    report_dir: Path,
) -> None:
    """
    Generate the quality-check report and save as Markdown + CSV.

    Parameters
    ----------
    df : pd.DataFrame
        State-filtered DataFrame.
    state_code : str
    state_name : str
    report_dir : Path
    """
    report_dir.mkdir(parents=True, exist_ok=True)
    log.info("Generating quality report for %s ...", state_name)

    n_rows, n_cols = df.shape
    lines: list[str] = []

    lines.append(f"# {state_name} Wildfire Dataset - Quality Report")
    lines.append(f"\n_Generated by Phase-1 Preprocessing Pipeline_\n")

    # 1. Overview
    lines.append(_md_header("1. Overview"))
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| State code | `{state_code}` |")
    lines.append(f"| Number of fire records | {n_rows:,} |")
    lines.append(f"| Number of columns | {n_cols:,} |")

    if COL_FIRE_YEAR in df.columns:
        years = sorted(df[COL_FIRE_YEAR].dropna().unique().astype(int).tolist())
        lines.append(f"| Years available | {years} |")
        lines.append(f"| Year range | {min(years)} - {max(years)} |")

    # 2. Fire Size Statistics
    lines.append(_md_header("2. Fire Size Statistics (acres)"))
    if COL_FIRE_SIZE in df.columns:
        fs = pd.to_numeric(df[COL_FIRE_SIZE], errors="coerce").dropna()
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Count | {len(fs):,} |")
        lines.append(f"| Mean | {fs.mean():.2f} |")
        lines.append(f"| Median | {fs.median():.2f} |")
        lines.append(f"| Std Dev | {fs.std():.2f} |")
        lines.append(f"| Min | {fs.min():.2f} |")
        lines.append(f"| 25th pct | {fs.quantile(0.25):.2f} |")
        lines.append(f"| 75th pct | {fs.quantile(0.75):.2f} |")
        lines.append(f"| 95th pct | {fs.quantile(0.95):.2f} |")
        lines.append(f"| 99th pct | {fs.quantile(0.99):.2f} |")
        lines.append(f"| Max | {fs.max():.2f} |")
    else:
        lines.append("_FIRE_SIZE column not present._")

    # 3. Fire Causes
    lines.append(_md_header("3. Fire Causes"))
    if COL_CAUSE in df.columns:
        vc = _safe_value_counts(df[COL_CAUSE], n=20)
        lines.append(f"| Cause | Count | Pct |")
        lines.append(f"|-------|-------|-----|")
        for cause, cnt in vc.items():
            lines.append(f"| {cause} | {cnt:,} | {cnt/n_rows*100:.1f}% |")
    else:
        lines.append("_NWCG_GENERAL_CAUSE column not present._")

    # 4. Counties
    lines.append(_md_header(f"4. Top {TOP_N_COUNTIES} Counties by Fire Count"))
    if COL_COUNTY in df.columns:
        vc = _safe_value_counts(df[COL_COUNTY], n=TOP_N_COUNTIES)
        total_counties = df[COL_COUNTY].nunique()
        lines.append(f"_Total unique counties: {total_counties}_\n")
        lines.append(f"| County | Count |")
        lines.append(f"|--------|-------|")
        for county, cnt in vc.items():
            lines.append(f"| {county} | {cnt:,} |")
    else:
        lines.append("_COUNTY column not present._")

    # 5. Geographic Extent
    lines.append(_md_header("5. Geographic Extent"))
    for col_name, label in [(COL_LATITUDE, "Latitude"), (COL_LONGITUDE, "Longitude")]:
        if col_name in df.columns:
            vals = pd.to_numeric(df[col_name], errors="coerce").dropna()
            lines.append(
                f"**{label}**: min={vals.min():.4f}  max={vals.max():.4f}  mean={vals.mean():.4f}"
            )

    # 6. Missing Values
    lines.append(_md_header("6. Missing Values"))
    null_counts = df.isnull().sum()
    null_pct    = null_counts / n_rows * 100
    missing_df  = (
        pd.DataFrame({"missing_count": null_counts, "missing_pct": null_pct.round(2)})
        .query("missing_count > 0")
        .sort_values("missing_pct", ascending=False)
    )
    cols_complete = (null_counts == 0).sum()
    lines.append(f"- Columns with **no** missing values : {cols_complete}/{n_cols}")
    lines.append(f"- Columns with **some** missing values : {len(missing_df)}/{n_cols}")
    if not missing_df.empty:
        lines.append(f"\n| Column | Missing Count | Missing % |")
        lines.append(f"|--------|--------------|-----------|")
        for col, row in missing_df.head(50).iterrows():
            lines.append(f"| {col} | {int(row.missing_count):,} | {row.missing_pct:.1f}% |")

    # Save missing_values.csv
    missing_csv_path = report_dir / "missing_values.csv"
    missing_df.reset_index().rename(columns={"index": "column"}).to_csv(
        missing_csv_path, index=False
    )
    log.info("Missing values CSV saved -> %s", missing_csv_path)

    # 7. Duplicate Rows
    lines.append(_md_header("7. Duplicate Rows"))
    dup_count = df.duplicated().sum()
    lines.append(f"- Exact duplicate rows : **{dup_count:,}** ({dup_count/n_rows*100:.2f}%)")

    # 8. Unique Identifiers
    lines.append(_md_header("8. Unique Identifiers"))
    for col, label in [
        (COL_FIRE_NAME, "Unique fire names"),
        (COL_AGENCY,    "Unique reporting agencies"),
        (COL_OWNER,     "Unique owner types"),
    ]:
        if col in df.columns:
            u = df[col].nunique(dropna=False)
            lines.append(f"- {label} : **{u:,}**")

    if COL_AGENCY in df.columns:
        lines.append(f"\n**Top {TOP_N_AGENCIES} Reporting Agencies:**\n")
        vc = _safe_value_counts(df[COL_AGENCY], n=TOP_N_AGENCIES)
        lines.append(f"| Agency | Count |")
        lines.append(f"|--------|-------|")
        for ag, cnt in vc.items():
            lines.append(f"| {ag} | {cnt:,} |")

    if COL_OWNER in df.columns:
        lines.append(f"\n**Owner Types:**\n")
        vc = _safe_value_counts(df[COL_OWNER])
        lines.append(f"| Owner | Count |")
        lines.append(f"|-------|-------|")
        for own, cnt in vc.items():
            lines.append(f"| {own} | {cnt:,} |")

    # 9. Fires per Year
    lines.append(_md_header("9. Fires per Year"))
    if COL_FIRE_YEAR in df.columns:
        vc = df[COL_FIRE_YEAR].value_counts().sort_index()
        lines.append(f"| Year | Fire Count |")
        lines.append(f"|------|-----------|")
        for yr, cnt in vc.items():
            lines.append(f"| {yr} | {cnt:,} |")

    # Write Markdown
    md_path = report_dir / "dataset_summary.md"
    md_path.write_text("\n".join(lines), encoding="utf-8")
    log.info("Quality report saved -> %s", md_path)
